<div class="content">
	<h4>Översikt</h4>
	<p>Ubisoft är utan tvekan en av världens största och skickligaste spelutvecklare. Denna studio har gett oss spelserier som: Assassin’s Creed, Prince of Persia, Rayman, Splinter Cell och många fler. Far Cry började dock som ett samarbete mellan studion och Crytek men efter lagliga dispyter var det slutligen Ubisoft som behöll rättigheterna. Första uppföljaren kom efter fyra år, och sedan dröjde det ytterligare lika många innan Far Cry 3 släpptes. Den långa utvecklingstiden gav dem möjligheten att förändra mycket av tidigare innehåll och med en historia som fokusera på protagonistens utveckling och den psykotiska Vaas hade FC3 alla förutsättningar för att lyckas.</p>

	<p>Rent kommersiellt gjorde spelet det med över sex miljoner sålda exemplar, men även sett ur den faktiska kvalitén var denna titel en solklar GOTY för många 2012. Det var i alla fall vad majoriteten av läsarna på PowerGamer ansåg när omröstningen var avgjord och alla val var räknade. Nu börjar det dra ihop sig för GOTY än en gång men innan dess har spelhösten 2014 fortfarande lite fläskiga titlar kvar att leverera, bland annat Far Cry 4. Till skillnad mot föregångaren vill inte Ubisoft vänta lika länge med denna serie utan det var tydligen dags igen två år senare, men kom FC4 för tidigt?</p>
	
	<div class="image-holder">
		<a href="#" class="image-magnify"></a>
		<img src="http://www.powergamer.se/imglibrary/nyheter/2014/11/FC4-Pagan-Min.jpg" />
		<p class="image-info">Om Far Cry 3 och 4 hade varit filmer skulle deras skurkar hetat Jokern och Bane.</p>
	</div>
	
	<p>Det korta svaret på ovanstående fråga är JA, för studion valde att vara lata och säkra. Alla som har spelat Far Cry 3 kommer direkt känna igen sig i det senaste alstret och istället för en fascinerande utveckling med huvudkaraktären får vi istället en ganska blek och ihålig protagonist. Ajay Ghale är ganska stel och tom, vi berörs inte i närheten lika mycket av honom som Jason Brody. Det är istället skurken Pagan Min som står för all karisma och charm bland karaktärerna, resterande individer är relativt stereotypiska och bidrar inte med större djup. Det sorgliga är då att under majoriteten av din speltid kommer du endast komma i kontakt med Pagan genom radiokonversationer istället för hans fysiska närvaro som verkligen visar att han är en värdig motsvarighet till Vaas.</p>
	<p>Om Far Cry 3 och 4 hade varit filmer skulle deras skurkar hetat Jokern och Bane, båda är genialiska men har egna unika drag som utmärker dem. Jag önskar att jag hade fått sett mer av Pagan Min under mina 15 timmar i spelets kampanj, men när han väl dök upp stal han showen varje gång. Nu har jag även sagt allt negativt om spelet, låt oss hugga in i de goda bitarna istället.</p>
	
	<img class="align-right" src="http://www.powergamer.se/imglibrary/nyheter/2014/11/FC4-Fortress.jpg" />
	
	<p>Den faktiska historien bakom FC4 handlar om Ajay som fått instruktioner från hans bortgånga moder att hennes aska ska spridas i hemlandet Kyrat, det påhittade landet som existerar i Himalayas bergskedja. När han väl kommer in i landet blir det snabbt kaotiskt för den självutnämnde kungen Pagan Min kommer och välkomnar honom, på hans egna brutala sätt. Du blir genast indragen i dispyten mellan konungen och rebellrörelsen Golden Path som gör allt för att störta tyrannen. Det är där du kommer in i bilden och genast kommer du igång med att göra små uppdrag som eskalerar allt eftersom du blir mer engagerad i deras kamp mot Min. Det finns också många olika individer som förser dig med uppdrag som har olika betydelse för den faktiska handlingen, precis som i föregångaren finns det gott om sidouppdrag. Det finns dock två ledare bland rebellerna som inte alltid kommer överens och du sätts då i en position när du måste välja vem du ska stödja. När du accepterar ett uppdrag blockeras det andra och du får leva med konsekvenserna av dina val, oavsett vem du i slutändan väljer att stöta. Jag nämnde också att det finns gott om sidouppdrag och det är bara förnamnet.</p>
	<p>Alla fiendeläger som du erövrar låser upp en rad olika problem som spelare kan tackla och det är bara vad som finns i de faktiska baserna, hela världen kryllar av saker att göra. Om du är en person som måste göra allt i ett spel som mig själv kommer du behöva sitta den dubbla tiden av vad kampanjen tar att genomföra, men med största sannolikhet kommer du ha väldigt få trista stunder. Du kan få uppdrag bara av att promenera runt i det vilda, helt plötsligt kan du behöva rädda en gisslan eller utplåna en fientlig konvoj. Det är bara två exempel av allt som kan hända när du inte gör ett faktiskt uppdrag, då dessa normalt har en utmärkt startpunkt som du utgår från. Den enorma variationen av uppdrag är helt fantastisk och det finns verkligen något för alla typer av spelare. Om du tycker om att köra fordon finns den typen av utmaningar, eller föredrar du kanske att slakta exotiska djur? Det kan du också göra. Du kanske rentav vill testa dina förmågor som ljudlös lönnmördare och slakta ledare eller frita fångar, Far Cry 4 ger dig denna möjlighet och mer därtill. Många av dessa är dessutom kopplade online till andra spelare och då blir det en helt annan typ av tävling om vem som kan göra det bäst.</p>
	
	<img class="align-left" src="http://www.powergamer.se/imglibrary/nyheter/2014/11/FC4-Snow.jpg" />
	
	<p>När vi ändå är inne på online-aspekten märks det tydligt att Ubisoft valt att satsa på detta hårt för det finns flera olika typer av upplevelser med andra spelare. I det faktiska spelet är det leaderboards som jag redan nämnt men det går även att helt sömlöst ha en andra spelare som gör dig sällskap under din session, då kan de mest galna sakerna uppstå. Far Cry 4 har en gigantisk arsenal av vapen och fordon och placerar man detta i händerna på en spelare kan man skapa fler explosioner än i en Michael Bay-rulle, dubbla sen detta när spelare två kommer in i bilden. Far Cry 4 är verkligen en enorm sandlåda som låter spelare ha roligt, men det finns även mer klassisk multiplayer. I dessa lägen kan du tävla mot andra på olika sätt, bland annat när två olika lag möts med olika egenskaper. I det ena laget finns dem klassiska Golden Path-rebellerna som har kraftfulla vapen och fordon som används för att köra över motståndarna med ren kraft. Det andra laget består istället av Pagan Mins elittrupp, Rakshas. Dessa förlitar sig mer på osynlighet och använder effektivt pilbågar, dem kan även manipulera faunan och nyttja lite magi för att skapa mer överraskning. Du spelar kanske Far Cry 4 för att utforska Kyrat på egen hand, men du borde verkligen uppleva vad multiplayern har att erbjuda också.</p>
	<div class="image-holder">
		<a href="#" class="image-magnify"></a>
		<img src="http://www.powergamer.se/imglibrary/nyheter/2014/11/FC4-Buzzer.jpg" />
		<p class="image-info">Det är faktiskt mer än bara ny miljö i Far Cry 4 men det krävs att du upplever det själv innan du kommer till den insikten.</p>
	</div>
	<p>Om du gillade Far Cry 3 kommer du med största sannolikhet ta till dig årets expansion… förlåt, jag menar spel. Det är faktiskt mer än bara ny miljö i Far Cry 4 men det krävs att du upplever det själv innan du kommer till den insikten. Jag gjorde allt som FC3 hade att erbjuda och på samma sätt har jag upplevt FC4, den enda tråkiga stunden var att samla alla kistor men när det kommer till variation i uppdrag, saker att se och utforska, vapenstilar att variera mellan och allt annat har det här spelet det mesta. Om du inte spelat föregångaren och behöver expandera ditt spelbibliotek till senaste generationens konsoler är Far Cry 4 ett måste, Kyrat är en värld som borde upplevas av alla.</p>
	
</div>

<div class="section-author">
	<img src="http://www.powergamer.se/imglibrary/nyheter/avatars/396/c02b373e3b9bc97cac7b47173137714a-bpfull.jpg">
	<span class="name">Anders Sandberg</span>
	<span class="title">Spelredaktör</span>
</div>